const questionsSimples = [
    // --- THEME 1 : Géographie basique ---
    { question: "Quelle est la capitale de la France ?", reponses: ["A. Lyon", "B. Marseille", "C. Paris", "D. Toulouse"], valid: 2 },
    { question: "Quel est le plus grand océan du monde ?", reponses: ["A. Atlantique", "B. Pacifique", "C. Indien", "D. Arctique"], valid: 1 },
    { question: "Quel pays est surnommé le Pays du Soleil Levant ?", reponses: ["A. Chine", "B. Japon", "C. Corée du Sud", "D. Thaïlande"], valid: 1 },
    { question: "Quelle est la capitale de l'Italie ?", reponses: ["A. Rome", "B. Venise", "C. Milan", "D. Naples"], valid: 0 },
    { question: "Sur quel continent se trouve le désert du Sahara ?", reponses: ["A. Asie", "B. Amérique", "C. Océanie", "D. Afrique"], valid: 3 },
    { question: "Quelle est la capitale de l'Espagne ?", reponses: ["A. Barcelone", "B. Séville", "C. Madrid", "D. Valence"], valid: 2 },
    { question: "Quel pays européen a la forme d'une botte ?", reponses: ["A. Grèce", "B. Italie", "C. Espagne", "D. Portugal"], valid: 1 },
    { question: "Quel océan sépare l'Europe de l'Amérique du Nord ?", reponses: ["A. Arctique", "B. Indien", "C. Pacifique", "D. Atlantique"], valid: 3 },
    { question: "Quel est le plus haut sommet du monde ?", reponses: ["A. Mont Blanc", "B. Kilimandjaro", "C. Everest", "D. Fuji"], valid: 2 },
    { question: "Dans quelle ville se trouve la Tour Eiffel ?", reponses: ["A. Londres", "B. Berlin", "C. Paris", "D. Bruxelles"], valid: 2 },

    // --- THEME 2 : Animaux ---
    { question: "Quel animal est réputé pour miauler ?", reponses: ["A. Le chien", "B. Le chat", "C. Le lapin", "D. Le hamster"], valid: 1 },
    { question: "Quel animal est surnommé le roi des animaux ?", reponses: ["A. Le tigre", "B. L'éléphant", "C. L'ours", "D. Le lion"], valid: 3 },
    { question: "Quel est le plus grand mammifère marin ?", reponses: ["A. Le requin blanc", "B. L'orque", "C. La baleine bleue", "D. Le dauphin"], valid: 2 },
    { question: "Quel oiseau marin noir et blanc ne sait pas voler ?", reponses: ["A. La mouette", "B. Le manchot", "C. Le pélican", "D. L'albatros"], valid: 1 },
    { question: "Quel grand mammifère terrestre possède une trompe ?", reponses: ["A. Le rhinocéros", "B. L'hippopotame", "C. La girafe", "D. L'éléphant"], valid: 3 },
    { question: "Combien de pattes a une araignée ?", reponses: ["A. 6", "B. 8", "C. 10", "D. 12"], valid: 1 },
    { question: "Quel insecte produit du miel ?", reponses: ["A. La guêpe", "B. Le bourdon", "C. La fourmi", "D. L'abeille"], valid: 3 },
    { question: "Comment s'appelle le petit de la vache ?", reponses: ["A. Le poulain", "B. L'agneau", "C. Le veau", "D. Le porcelet"], valid: 2 },
    { question: "Quel célèbre poisson clown cherche son fils dans l'océan ?", reponses: ["A. Dory", "B. Marin", "C. Nemo", "D. Bubulle"], valid: 1 },
    { question: "Quel animal terrestre a le plus long cou ?", reponses: ["A. Le chameau", "B. L'autruche", "C. La girafe", "D. Le lama"], valid: 2 },

    // --- THEME 3 : Corps humain ---
    { question: "Quel organe nous permet de respirer ?", reponses: ["A. Le foie", "B. L'estomac", "C. Les poumons", "D. Les reins"], valid: 2 },
    { question: "Quel organe pompe le sang dans notre corps ?", reponses: ["A. Le cœur", "B. Le cerveau", "C. Le foie", "D. Les poumons"], valid: 0 },
    { question: "Quel sens est associé aux yeux ?", reponses: ["A. L'ouïe", "B. Le goût", "C. Le toucher", "D. La vue"], valid: 3 },
    { question: "De quelle couleur est le sang humain chargé en oxygène ?", reponses: ["A. Bleu", "B. Vert", "C. Rouge", "D. Violet"], valid: 2 },
    { question: "Combien de doigts y a-t-il sur une seule main humaine ?", reponses: ["A. 4", "B. 5", "C. 6", "D. 10"], valid: 1 },
    { question: "Comment appelle-t-on l'ensemble des os de la tête ?", reponses: ["A. Le crâne", "B. Le bassin", "C. Le fémur", "D. Les côtes"], valid: 0 },
    { question: "Quel organe est le principal responsable de l'audition ?", reponses: ["A. Le nez", "B. La langue", "C. L'oreille", "D. L'œil"], valid: 2 },
    { question: "Quel est l'organe le plus étendu du corps humain ?", reponses: ["A. Le foie", "B. Les intestins", "C. La peau", "D. Les poumons"], valid: 2 },
    { question: "Quel liquide naturel se trouve dans la bouche ?", reponses: ["A. L'acide", "B. La sueur", "C. Les larmes", "D. La salive"], valid: 3 },
    { question: "Comment s'appellent les poils situés au-dessus des yeux ?", reponses: ["A. Les cils", "B. Les sourcils", "C. La moustache", "D. La barbe"], valid: 1 },

    // --- THEME 4 : Mathématiques et Temps ---
    { question: "Combien font 2 + 2 ?", reponses: ["A. 2", "B. 3", "C. 4", "D. 5"], valid: 2 },
    { question: "Combien y a-t-il de jours dans une semaine complète ?", reponses: ["A. 5", "B. 6", "C. 7", "D. 8"], valid: 2 },
    { question: "Combien y a-t-il de mois dans une année ?", reponses: ["A. 10", "B. 11", "C. 12", "D. 13"], valid: 2 },
    { question: "Combien d'heures compte une journée entière ?", reponses: ["A. 12", "B. 24", "C. 48", "D. 60"], valid: 1 },
    { question: "Combien y a-t-il de minutes dans une heure ?", reponses: ["A. 30", "B. 60", "C. 90", "D. 100"], valid: 1 },
    { question: "Combien de jours compte une année non bissextile ?", reponses: ["A. 364", "B. 365", "C. 366", "D. 300"], valid: 1 },
    { question: "Quelle est la moitié de 10 ?", reponses: ["A. 2", "B. 4", "C. 5", "D. 6"], valid: 2 },
    { question: "Combien de côtés possède un triangle ?", reponses: ["A. 2", "B. 3", "C. 4", "D. 5"], valid: 1 },
    { question: "Combien de côtés possède un carré ?", reponses: ["A. 3", "B. 4", "C. 5", "D. 6"], valid: 1 },
    { question: "Quel est le double de 50 ?", reponses: ["A. 25", "B. 75", "C. 100", "D. 150"], valid: 2 },

    // --- THEME 5 : Couleurs et Nature ---
    { question: "De quelle couleur est un ciel dégagé en journée ?", reponses: ["A. Vert", "B. Rouge", "C. Jaune", "D. Bleu"], valid: 3 },
    { question: "Quelle couleur obtient-on en mélangeant du jaune et du bleu ?", reponses: ["A. Rouge", "B. Violet", "C. Vert", "D. Orange"], valid: 2 },
    { question: "Quelle couleur obtient-on en mélangeant du rouge et du blanc ?", reponses: ["A. Rose", "B. Violet", "C. Marron", "D. Orange"], valid: 0 },
    { question: "De quelle couleur est une émeraude ?", reponses: ["A. Rouge", "B. Bleu", "C. Vert", "D. Jaune"], valid: 2 },
    { question: "Quelle couleur obtient-on en mélangeant du rouge et du jaune ?", reponses: ["A. Marron", "B. Rose", "C. Orange", "D. Vert"], valid: 2 },
    { question: "En quelle saison la neige tombe-t-elle généralement en Europe ?", reponses: ["A. Printemps", "B. Été", "C. Automne", "D. Hiver"], valid: 3 },
    { question: "En quelle saison les feuilles des arbres tombent-elles ?", reponses: ["A. Printemps", "B. Été", "C. Automne", "D. Hiver"], valid: 2 },
    { question: "De quelle couleur est généralement le tronc d'un arbre ?", reponses: ["A. Vert", "B. Marron", "C. Noir", "D. Blanc"], valid: 1 },
    { question: "Comment s'appelle l'eau qui tombe des nuages ?", reponses: ["A. La rosée", "B. La grêle", "C. La brume", "D. La pluie"], valid: 3 },
    { question: "Quelle fleur jaune tourne toujours vers le soleil ?", reponses: ["A. La rose", "B. Le tournesol", "C. La tulipe", "D. L'orchidée"], valid: 1 },

    // --- THEME 6 : Nourriture ---
    { question: "Quel fruit jaune est connu pour sa forme allongée et courbée ?", reponses: ["A. Le citron", "B. L'ananas", "C. La banane", "D. La poire"], valid: 2 },
    { question: "Quel légume orange est associé aux lapins ?", reponses: ["A. Le potiron", "B. La carotte", "C. Le poivron", "D. La tomate"], valid: 1 },
    { question: "Quelle boisson blanche est produite par les vaches ?", reponses: ["A. L'eau", "B. Le jus", "C. Le lait", "D. Le yaourt"], valid: 2 },
    { question: "Quel est l'ingrédient principal pour faire du pain ?", reponses: ["A. Le sucre", "B. La farine", "C. L'œuf", "D. Le beurre"], valid: 1 },
    { question: "Quel petit fruit rouge porte ses pépins à l'extérieur ?", reponses: ["A. La cerise", "B. La framboise", "C. La fraise", "D. La mûre"], valid: 2 },
    { question: "Quel plat rond, d'origine italienne, est souvent découpé en parts ?", reponses: ["A. La quiche", "B. La tarte", "C. La crêpe", "D. La pizza"], valid: 3 },
    { question: "Quelle pâte italienne prend la forme de longs fils fins ?", reponses: ["A. Les macaronis", "B. Les spaghettis", "C. Les farfalles", "D. Les pennes"], valid: 1 },
    { question: "Quel liquide sucré les abeilles fabriquent-elles ?", reponses: ["A. Le sirop", "B. Le miel", "C. Le nectar", "D. La confiture"], valid: 1 },
    { question: "Quel légume fait souvent pleurer quand on le coupe ?", reponses: ["A. L'oignon", "B. L'ail", "C. L'échalote", "D. Le poireau"], valid: 0 },
    { question: "Quel aliment coupe-t-on pour faire des frites ?", reponses: ["A. La courgette", "B. La carotte", "C. La pomme de terre", "D. Le navet"], valid: 2 },

    // --- THEME 7 : Ciel et Espace ---
    { question: "Quelle planète est surnommée la Planète Rouge ?", reponses: ["A. Vénus", "B. Jupiter", "C. Mars", "D. Saturne"], valid: 2 },
    { question: "Sur quelle planète vivons-nous ?", reponses: ["A. Mercure", "B. La Terre", "C. Mars", "D. Neptune"], valid: 1 },
    { question: "Quel est le contraire du jour ?", reponses: ["A. Le matin", "B. L'aube", "C. Le soir", "D. La nuit"], valid: 3 },
    { question: "Quelle est l'étoile la plus proche de la Terre ?", reponses: ["A. L'Étoile Polaire", "B. Sirius", "C. Le Soleil", "D. Véga"], valid: 2 },
    { question: "Combien de planètes composent actuellement notre système solaire ?", reponses: ["A. 7", "B. 8", "C. 9", "D. 10"], valid: 1 },
    { question: "Dans quelle galaxie se trouve la Terre ?", reponses: ["A. Andromède", "B. Le Centaure", "C. La Voie Lactée", "D. Orion"], valid: 2 },
    { question: "Quelle est la forme globale de la Terre ?", reponses: ["A. Un cube", "B. Un disque plat", "C. Un cylindre", "D. Une sphère"], valid: 3 },
    { question: "Quel astre naturel éclaire nos nuits et tourne autour de la Terre ?", reponses: ["A. Le Soleil", "B. La Lune", "C. Mars", "D. Une comète"], valid: 1 },
    { question: "Quelle force invisible nous maintient les pieds au sol ?", reponses: ["A. Le magnétisme", "B. L'électricité", "C. La gravité", "D. La friction"], valid: 2 },
    { question: "Quel instrument utilise-t-on pour observer les étoiles de plus près ?", reponses: ["A. Un microscope", "B. Des jumelles", "C. Une loupe", "D. Un télescope"], valid: 3 },

    // --- THEME 8 : Culture, Arts et Fiction ---
    { question: "Quel célèbre artiste a peint la Joconde ?", reponses: ["A. Picasso", "B. Van Gogh", "C. Léonard de Vinci", "D. Monet"], valid: 2 },
    { question: "Dans quel type de bâtiment expose-t-on des œuvres d'art au public ?", reponses: ["A. Un musée", "B. Un cinéma", "C. Un théâtre", "D. Une bibliothèque"], valid: 0 },
    { question: "Quel personnage Disney est une souris avec un short rouge ?", reponses: ["A. Donald", "B. Dingo", "C. Pluto", "D. Mickey"], valid: 3 },
    { question: "Comment s'appelle le célèbre jeune sorcier à lunettes de J.K. Rowling ?", reponses: ["A. Ron Weasley", "B. Drago Malefoy", "C. Harry Potter", "D. Voldemort"], valid: 2 },
    { question: "Quelle est la langue officielle de la France ?", reponses: ["A. L'anglais", "B. L'espagnol", "C. Le français", "D. L'allemand"], valid: 2 },
    { question: "Quel célèbre plombier moustachu est la mascotte de Nintendo ?", reponses: ["A. Luigi", "B. Sonic", "C. Link", "D. Mario"], valid: 3 },
    { question: "Quel instrument de musique possède des touches noires et blanches ?", reponses: ["A. La guitare", "B. Le violon", "C. La flûte", "D. Le piano"], valid: 3 },
    { question: "Quel super-héros de Gotham City s'habille en chauve-souris ?", reponses: ["A. Superman", "B. Spiderman", "C. Batman", "D. Iron Man"], valid: 2 },
    { question: "Comment appelle-t-on un livre qui regroupe des cartes de géographie ?", reponses: ["A. Un dictionnaire", "B. Un atlas", "C. Un roman", "D. Une encyclopédie"], valid: 1 },
    { question: "Dans quel film d'animation Disney trouve-t-on les sœurs Elsa et Anna ?", reponses: ["A. Raiponce", "B. Vaiana", "C. La Belle et la Bête", "D. La Reine des Neiges"], valid: 3 },

    // --- THEME 9 : Objets et Vie quotidienne ---
    { question: "Quel outil doté de deux lames croisées sert à couper du papier ?", reponses: ["A. Un couteau", "B. Un cutter", "C. Des ciseaux", "D. Une scie"], valid: 2 },
    { question: "Avec quoi écrit-on traditionnellement sur un tableau noir à l'école ?", reponses: ["A. Un stylo", "B. De la craie", "C. Un feutre", "D. Un crayon"], valid: 1 },
    { question: "Comment s'appelle un véhicule écologique à deux roues propulsé par des pédales ?", reponses: ["A. Une moto", "B. Un scooter", "C. Une voiture", "D. Un vélo"], valid: 3 },
    { question: "Quel appareil électroménager sert à laver les vêtements ?", reponses: ["A. Le four", "B. Le lave-vaisselle", "C. Le réfrigérateur", "D. Le lave-linge"], valid: 3 },
    { question: "Quel petit objet métallique utilise-t-on pour déverrouiller une porte ?", reponses: ["A. Une pièce", "B. Un tournevis", "C. Une clé", "D. Un clou"], valid: 2 },
    { question: "Quel objet s'ouvre au-dessus de la tête pour se protéger de la pluie ?", reponses: ["A. Un chapeau", "B. Un bouclier", "C. Un parapluie", "D. Une tente"], valid: 2 },
    { question: "Quel appareil portatif permet aujourd'hui d'appeler n'importe qui de n'importe où ?", reponses: ["A. Un ordinateur", "B. Un téléviseur", "C. Une radio", "D. Un téléphone portable"], valid: 3 },
    { question: "Sur quel meuble confortable s'allonge-t-on pour dormir la nuit ?", reponses: ["A. Une chaise", "B. Un lit", "C. Un bureau", "D. Une armoire"], valid: 1 },
    { question: "Dans quelle pièce de la maison trouve-t-on généralement la douche ou la baignoire ?", reponses: ["A. La cuisine", "B. Le salon", "C. La salle de bain", "D. Le garage"], valid: 2 },
    { question: "Quel outil gradué en centimètres sert à tracer des lignes droites ?", reponses: ["A. Une équerre", "B. Un compas", "C. Une règle", "D. Un rapporteur"], valid: 2 },

    // --- THEME 10 : Sports et Loisirs ---
    { question: "Quel sport collectif se joue avec un ballon rond et les pieds ?", reponses: ["A. Le rugby", "B. Le handball", "C. Le basketball", "D. Le football"], valid: 3 },
    { question: "Quel sport pratiquait professionnellement le champion Rafael Nadal ?", reponses: ["A. Le golf", "B. Le tennis", "C. L'escrime", "D. Le cyclisme"], valid: 1 },
    { question: "Quel objet lourd fait-on rouler pour faire tomber des quilles au bowling ?", reponses: ["A. Une roue", "B. Un ballon", "C. Une boule", "D. Un disque"], valid: 2 },
    { question: "Comment s'appelle le sport qui consiste à se déplacer dans l'eau d'une piscine ?", reponses: ["A. Le plongeon", "B. L'aviron", "C. Le water-polo", "D. La natation"], valid: 3 },
    { question: "Quelle est la couleur de la ceinture d'un débutant au Judo ?", reponses: ["A. Noire", "B. Rouge", "C. Verte", "D. Blanche"], valid: 3 },
    { question: "Comment s'appellent les célèbres jeux sportifs mondiaux organisés tous les 4 ans ?", reponses: ["A. Le Mondial", "B. Les Jeux Olympiques", "C. Le Tour de France", "D. La Coupe d'Europe"], valid: 1 },
    { question: "Dans quel sport de raquette tape-t-on dans un volant ?", reponses: ["A. Le tennis de table", "B. Le squash", "C. Le badminton", "D. Le tennis"], valid: 2 },
    { question: "Sur quelle surface se joue le célèbre tournoi de Roland-Garros ?", reponses: ["A. Le gazon", "B. Le béton", "C. La terre battue", "D. Le parquet"], valid: 2 },
    { question: "Que doit-on lancer dans un panier haut de 3m05 au basketball ?", reponses: ["A. Une balle", "B. Un volant", "C. Un palet", "D. Un ballon"], valid: 3 },
    { question: "Quel sport d'hiver consiste à glisser sur la neige avec deux longues planches ?", reponses: ["A. Le patinage", "B. Le bobsleigh", "C. Le snowboard", "D. Le ski"], valid: 3 }
];