const questionsAvancees = [
    // --- THEME 1 : Géographie Avancée ---
    { question: "Quelle est la capitale du Bhoutan ?", reponses: ["A. Katmandou", "B. Thimphou", "C. Dacca", "D. Kaboul"], valid: 1 },
    { question: "Quel est le lac le plus profond du monde ?", reponses: ["A. Le lac Supérieur", "B. Le lac Victoria", "C. Le lac Titicaca", "D. Le lac Baïkal"], valid: 3 },
    { question: "Quel pays d'Afrique n'a jamais été colonisé par une puissance européenne ?", reponses: ["A. L'Éthiopie", "B. Le Liberia", "C. L'Égypte", "D. Le Maroc"], valid: 0 },
    { question: "Quel est le pays qui possède le plus grand nombre d'îles au monde ?", reponses: ["A. L'Indonésie", "B. Les Philippines", "C. La Suède", "D. Le Japon"], valid: 2 },
    { question: "Quels sont les deux seuls pays d'Amérique du Sud qui n'ont aucun accès à la mer ?", reponses: ["A. Bolivie et Paraguay", "B. Pérou et Équateur", "C. Uruguay et Paraguay", "D. Colombie et Bolivie"], valid: 0 },
    { question: "Comment s'appelle le détroit qui sépare la Russie de l'Alaska ?", reponses: ["A. Le détroit de Magellan", "B. Le détroit de Béring", "C. Le détroit de Gibraltar", "D. Le détroit d'Ormuz"], valid: 1 },
    { question: "Quel est le plus petit pays indépendant du monde en superficie (hors Vatican) ?", reponses: ["A. Monaco", "B. Nauru", "C. Tuvalu", "D. Saint-Marin"], valid: 0 },
    { question: "Quelle est l'île la plus peuplée du monde ?", reponses: ["A. Honshu", "B. Java", "C. La Grande-Bretagne", "D. Sumatra"], valid: 1 },
    { question: "Sur quel fleuve se trouve la majestueuse cascade Victoria ?", reponses: ["A. Le Nil", "B. Le Congo", "C. Le Zambèze", "D. Le Niger"], valid: 2 },
    { question: "Quelle est la plus haute chute d'eau du monde ?", reponses: ["A. Les chutes du Niagara", "B. Salto Ángel", "C. Les chutes d'Iguazú", "D. Yosemite Falls"], valid: 1 },

    // --- THEME 2 : Animaux et Nature Avancés ---
    { question: "Quel animal marin est biologiquement considéré comme immortel ?", reponses: ["A. Le requin du Groenland", "B. La tortue luth", "C. L'éponge de verre", "D. La méduse Turritopsis dohrnii"], valid: 3 },
    { question: "Quel est le seul oiseau capable de voler en marche arrière ?", reponses: ["A. Le colibri", "B. Le martin-pêcheur", "C. L'hirondelle", "D. Le martinet"], valid: 0 },
    { question: "Combien de cœurs possède un ver de terre (lombric) ?", reponses: ["A. 1", "B. 3", "C. 5", "D. 7"], valid: 2 },
    { question: "De quoi est principalement composée la corne d'un rhinocéros ?", reponses: ["A. D'os", "B. D'ivoire", "C. De cartilage", "D. De kératine"], valid: 3 },
    { question: "Quel animal possède des pupilles de forme rectangulaire ?", reponses: ["A. Le chat", "B. La chèvre", "C. Le hibou", "D. Le crocodile"], valid: 1 },
    { question: "Quel est le temps de gestation moyen d'un éléphant d'Afrique ?", reponses: ["A. 9 mois", "B. 12 mois", "C. 18 mois", "D. 22 mois"], valid: 3 },
    { question: "Comment appelle-t-on la peur phobique des araignées ?", reponses: ["A. L'arachnophobie", "B. L'entomophobie", "C. L'agoraphobie", "D. L'ophidiophobie"], valid: 0 },
    { question: "Quel mammifère est réputé pour avoir l'empreinte digitale la plus proche de celle de l'homme ?", reponses: ["A. Le chimpanzé", "B. Le koala", "C. Le gorille", "D. Le paresseux"], valid: 1 },
    { question: "Quelle espèce de requin est considérée comme le plus grand poisson vivant ?", reponses: ["A. Le grand requin blanc", "B. Le requin-baleine", "C. Le requin pèlerin", "D. Le requin-tigre"], valid: 1 },
    { question: "Quel est l'oiseau volant le plus lourd du monde ?", reponses: ["A. L'autruche", "B. Le condor des Andes", "C. L'outarde kori", "D. L'albatros hurleur"], valid: 2 },

    // --- THEME 3 : Corps humain et Biologie Avancés ---
    { question: "Quel est le nom du plus petit muscle du corps humain ?", reponses: ["A. Le muscle stapédien (étrier)", "B. Le muscle ciliaire", "C. Le sartorius", "D. Le sphincter pupillaire"], valid: 0 },
    { question: "Quel est le seul os du corps humain qui n'est articulé avec aucun autre os ?", reponses: ["A. La rotule", "B. Le coccyx", "C. L'os hyoïde", "D. Le sternum"], valid: 2 },
    { question: "Comment s'appelle l'enzyme présente dans la salive qui commence la digestion des glucides ?", reponses: ["A. La pepsine", "B. L'amylase", "C. La lipase", "D. La trypsine"], valid: 1 },
    { question: "Quelle est la substance la plus dure du corps humain ?", reponses: ["A. Le fémur", "B. La dentine", "C. Le cartilage hyalin", "D. L'émail dentaire"], valid: 3 },
    { question: "Où les globules rouges sont-ils principalement produits chez l'adulte ?", reponses: ["A. Dans le foie", "B. Dans la rate", "C. Dans la moelle osseuse", "D. Dans les reins"], valid: 2 },
    { question: "Quel est le terme médical exact pour désigner la 'pomme d'Adam' ?", reponses: ["A. Le cartilage thyroïde", "B. L'épiglotte", "C. Le larynx", "D. La trachée"], valid: 0 },
    { question: "Quelle hormone est principalement responsable de la régulation du cycle veille-sommeil ?", reponses: ["A. La sérotonine", "B. La dopamine", "C. Le cortisol", "D. La mélatonine"], valid: 3 },
    { question: "Combien de lobes principaux possède le poumon droit de l'être humain ?", reponses: ["A. 1", "B. 2", "C. 3", "D. 4"], valid: 2 },
    { question: "Quel nerf crânien est le plus long et innerve de nombreux organes de l'abdomen ?", reponses: ["A. Le nerf optique", "B. Le nerf trijumeau", "C. Le nerf facial", "D. Le nerf vague"], valid: 3 },
    { question: "Quel élément du sang est principalement responsable de la coagulation ?", reponses: ["A. Les leucocytes", "B. Les hématies", "C. Les thrombocytes (plaquettes)", "D. Le plasma"], valid: 2 },

    // --- THEME 4 : Mathématiques et Logique Avancées ---
    { question: "Quelle est la dérivée de la fonction f(x) = sin(x) ?", reponses: ["A. -cos(x)", "B. cos(x)", "C. -sin(x)", "D. tan(x)"], valid: 1 },
    { question: "Comment appelle-t-on un polygone régulier possédant 12 côtés ?", reponses: ["A. Un décagone", "B. Un hendécagone", "C. Un dodécagone", "D. Un icosagone"], valid: 2 },
    { question: "Quelle est la suite du nombre de Fibonacci : 1, 1, 2, 3, 5, 8, 13... ?", reponses: ["A. 18", "B. 21", "C. 24", "D. 26"], valid: 1 },
    { question: "Comment appelle-t-on un nombre premier qui est égal à une puissance de 2 moins 1 (ex: 3, 7, 31) ?", reponses: ["A. Un nombre de Fermat", "B. Un nombre parfait", "C. Un nombre de Mersenne", "D. Un nombre d'Euler"], valid: 2 },
    { question: "Combien d'arêtes possède un icosaèdre ?", reponses: ["A. 12", "B. 20", "C. 30", "D. 60"], valid: 2 },
    { question: "Qui a finalement démontré le dernier théorème de Fermat en 1994 ?", reponses: ["A. Alan Turing", "B. John Nash", "C. Andrew Wiles", "D. Cédric Villani"], valid: 2 },
    { question: "Quelle est la somme totale des angles internes d'un hexagone ?", reponses: ["A. 360°", "B. 540°", "C. 720°", "D. 900°"], valid: 2 },
    { question: "Quel est le nombre 11 écrit en système binaire ?", reponses: ["A. 1001", "B. 1010", "C. 1011", "D. 1100"], valid: 2 },
    { question: "Quel est le plus grand nombre romain que l'on peut écrire de façon standard sans macron (barre) et sans répéter 4 fois un symbole ?", reponses: ["A. 1999 (MCMXCIX)", "B. 2999 (MMCMXCIX)", "C. 3999 (MMMCMXCIX)", "D. 4999 (MMMMCMXCIX)"], valid: 2 },
    { question: "Par quelle décimale commence le nombre d'Euler (e) ?", reponses: ["A. 1,61...", "B. 2,71...", "C. 3,14...", "D. 9,81..."], valid: 1 },

    // --- THEME 5 : Sciences, Chimie et Physique Avancées ---
    { question: "Quel est l'élément chimique le plus abondant dans l'univers ?", reponses: ["A. L'oxygène", "B. Le carbone", "C. L'hélium", "D. L'hydrogène"], valid: 3 },
    { question: "Quelle est la température exacte du zéro absolu en degrés Celsius ?", reponses: ["A. -100°C", "B. -273,15°C", "C. -373,15°C", "D. -459,67°C"], valid: 1 },
    { question: "Comment appelle-t-on le passage direct de l'état solide à l'état gazeux ?", reponses: ["A. La condensation", "B. L'évaporation", "C. La sublimation", "D. La fusion"], valid: 2 },
    { question: "Quelle particule élémentaire est le médiateur de la force électromagnétique ?", reponses: ["A. L'électron", "B. Le quark", "C. Le gluon", "D. Le photon"], valid: 3 },
    { question: "Dans quel état de la matière se trouve la grande majorité du Soleil ?", reponses: ["A. Solide", "B. Liquide", "C. Gazeux", "D. Plasma"], valid: 3 },
    { question: "Quel est le métal le plus abondant dans la croûte terrestre ?", reponses: ["A. Le fer", "B. Le cuivre", "C. L'aluminium", "D. L'or"], valid: 2 },
    { question: "Que signifie le 'c' dans la célèbre équation E=mc² ?", reponses: ["A. La constante de gravitation", "B. La célérité (vitesse de la lumière)", "C. La charge électrique", "D. La chaleur massique"], valid: 1 },
    { question: "Qui a découvert la pénicilline en 1928 ?", reponses: ["A. Louis Pasteur", "B. Marie Curie", "C. Alexander Fleming", "D. Robert Koch"], valid: 2 },
    { question: "Quel est le nom de la première loi de la thermodynamique ?", reponses: ["A. La loi de conservation de l'énergie", "B. Le principe d'entropie", "C. La loi de l'action et de la réaction", "D. La constante de Planck"], valid: 0 },
    { question: "Quel est l'élément naturel le plus lourd du tableau périodique ?", reponses: ["A. Le plomb", "B. L'uranium", "C. Le mercure", "D. Le tungstène"], valid: 1 },

    // --- THEME 6 : Gastronomie Avancée ---
    { question: "Quelle réaction chimique est responsable du brunissement et de la saveur de la viande cuite ?", reponses: ["A. La fermentation lactique", "B. L'oxydation", "C. La réaction de Maillard", "D. La caramélisation"], valid: 2 },
    { question: "Quelle est l'épice la plus chère du monde au kilo ?", reponses: ["A. La vanille", "B. La cardamome", "C. Le safran", "D. La noix de muscade"], valid: 2 },
    { question: "Quel célèbre fromage français détient le record de la plus ancienne AOC (1925) ?", reponses: ["A. Le Camembert de Normandie", "B. Le Roquefort", "C. Le Comté", "D. Le Brie de Meaux"], valid: 1 },
    { question: "Que mesure exactement l'échelle de Scoville ?", reponses: ["A. L'acidité d'un agrume", "B. La force et le piquant d'un piment", "C. L'amertume du chocolat", "D. Le taux d'alcool d'une liqueur"], valid: 1 },
    { question: "Quel poisson, extrêmement toxique s'il est mal préparé, est un mets de luxe au Japon (Fugu) ?", reponses: ["A. Le poisson-globe", "B. Le poisson-lune", "C. La murène", "D. Le thon rouge"], valid: 0 },
    { question: "De quel pays est originaire le célèbre vin liquoreux 'Tokaji' ?", reponses: ["A. L'Italie", "B. La Grèce", "C. La Hongrie", "D. L'Autriche"], valid: 2 },
    { question: "Quel cépage est exclusivement utilisé pour produire les grands vins rouges de Bourgogne ?", reponses: ["A. Le Cabernet Sauvignon", "B. Le Merlot", "C. La Syrah", "D. Le Pinot Noir"], valid: 3 },
    { question: "Quel est l'ingrédient principal utilisé pour confectionner la vraie pâte d'amande (massepain) ?", reponses: ["A. La pistache", "B. Le miel", "C. L'amande", "D. La noix de pécan"], valid: 2 },
    { question: "Comment appelle-t-on le champignon microscopique utilisé pour faire lever le pain ?", reponses: ["A. La présure", "B. Le levain", "C. La levure de boulanger", "D. Le bicarbonate"], valid: 2 },
    { question: "Dans la vraie recette italienne de la sauce Carbonara, quelle viande utilise-t-on ?", reponses: ["A. Des lardons fumés", "B. Du Guanciale", "C. Du jambon de Parme", "D. De la Pancetta"], valid: 1 },

    // --- THEME 7 : Ciel et Astronomie Avancés ---
    { question: "Quelle est la plus grande lune de notre système solaire ?", reponses: ["A. Titan", "B. Europe", "C. Io", "D. Ganymède"], valid: 3 },
    { question: "Comment appelle-t-on la frontière immatérielle autour d'un trou noir d'où rien ne peut s'échapper ?", reponses: ["A. Le disque d'accrétion", "B. La singularité", "C. L'horizon des événements", "D. Le point de non-retour"], valid: 2 },
    { question: "Quelle est la galaxie majeure la plus proche de notre Voie lactée ?", reponses: ["A. La galaxie du Sombrero", "B. La galaxie d'Andromède", "C. Le Grand Nuage de Magellan", "D. Messier 87"], valid: 1 },
    { question: "Qui a découvert en 1610 les quatre plus grandes lunes de Jupiter ?", reponses: ["A. Nicolas Copernic", "B. Johannes Kepler", "C. Galilée", "D. Isaac Newton"], valid: 2 },
    { question: "Quelle est l'étoile la plus brillante du ciel nocturne depuis la Terre ?", reponses: ["A. Bételgeuse", "B. Proxima du Centaure", "C. Sirius", "D. Alpha Ursae Minoris"], valid: 2 },
    { question: "De quoi sont principalement composés les magnifiques anneaux de Saturne ?", reponses: ["A. De fer et de nickel", "B. De gaz gelé", "C. De particules de glace et de poussière", "D. De roches volcaniques"], valid: 2 },
    { question: "Comment s'appelle l'immense nuage sphérique de comètes qui entoure notre système solaire ?", reponses: ["A. La ceinture de Kuiper", "B. Le nuage d'Oort", "C. La ceinture d'astéroïdes", "D. L'héliosphère"], valid: 1 },
    { question: "Quel terme désigne l'instant précis où le Soleil traverse l'équateur céleste ?", reponses: ["A. Le solstice", "B. Le périhélie", "C. L'équinoxe", "D. L'aphélie"], valid: 2 },
    { question: "Quelle planète de notre système solaire possède l'orbite la plus excentrique (la moins circulaire) ?", reponses: ["A. Mercure", "B. Mars", "C. Uranus", "D. Pluton"], valid: 0 },
    { question: "Quelle sonde spatiale a survolé et photographié Pluton pour la première fois en 2015 ?", reponses: ["A. Voyager 1", "B. Cassini", "C. Curiosity", "D. New Horizons"], valid: 3 },

    // --- THEME 8 : Culture, Histoire et Arts Avancés ---
    { question: "Quel philosophe politique a écrit 'Le Prince' au XVIe siècle ?", reponses: ["A. Thomas Hobbes", "B. Jean-Jacques Rousseau", "C. Machiavel", "D. John Locke"], valid: 2 },
    { question: "Qui fut le tout premier empereur de l'Empire romain ?", reponses: ["A. Jules César", "B. Auguste (Octave)", "C. Néron", "D. Trajan"], valid: 1 },
    { question: "Quel artiste surréaliste a peint 'La Persistance de la mémoire' (les montres molles) ?", reponses: ["A. René Magritte", "B. Pablo Picasso", "C. Joan Miró", "D. Salvador Dalí"], valid: 3 },
    { question: "Où a été signé le traité de paix qui a officiellement mis fin à la Première Guerre mondiale ?", reponses: ["A. À Paris", "B. À Genève", "C. À Versailles", "D. À Londres"], valid: 2 },
    { question: "À quelle époque musicale appartient principalement le compositeur Jean-Sébastien Bach ?", reponses: ["A. La Renaissance", "B. La période Baroque", "C. La période Classique", "D. La période Romantique"], valid: 1 },
    { question: "Quel est le nom du dernier Tsar de Russie, assassiné en 1918 ?", reponses: ["A. Alexandre III", "B. Pierre le Grand", "C. Ivan le Terrible", "D. Nicolas II"], valid: 3 },
    { question: "En quelle année le mur de Berlin a-t-il officiellement chuté ?", reponses: ["A. 1987", "B. 1989", "C. 1990", "D. 1991"], valid: 1 },
    { question: "À quel aède de l'Antiquité grecque attribue-t-on les épopées de l'Iliade et l'Odyssée ?", reponses: ["A. Hésiode", "B. Sophocle", "C. Homère", "D. Virgile"], valid: 2 },
    { question: "Quel style architectural se caractérise par des arcs-boutants, des croisées d'ogives et des vitraux ?", reponses: ["A. L'art roman", "B. L'art gothique", "C. L'architecture byzantine", "D. L'architecture néoclassique"], valid: 1 },
    { question: "Quel était le nom de la caste des guerriers japonais, officiellement abolie au XIXe siècle ?", reponses: ["A. Les Ninjas", "B. Les Shoguns", "C. Les Samouraïs", "D. Les Ronins"], valid: 2 },

    // --- THEME 9 : Informatique et Code (Le défi Ynov) ---
    { question: "Que signifie l'acronyme HTTP ?", reponses: ["A. HyperText Transfer Protocol", "B. HyperText Transmission Process", "C. Hyperlink Text Transfer Program", "D. Host To Terminal Protocol"], valid: 0 },
    { question: "Quel est le port par défaut utilisé pour une connexion sécurisée HTTPS ?", reponses: ["A. 21", "B. 80", "C. 443", "D. 8080"], valid: 2 },
    { question: "Qui est reconnue historiquement comme la toute première programmeuse informatique ?", reponses: ["A. Grace Hopper", "B. Margaret Hamilton", "C. Hedy Lamarr", "D. Ada Lovelace"], valid: 3 },
    { question: "Dans le versioning Git, quelle commande permet de valider et sauvegarder ses changements en local ?", reponses: ["A. git push", "B. git add", "C. git commit", "D. git save"], valid: 2 },
    { question: "Quelle est la complexité temporelle algorithmique (Big O) d'une recherche dichotomique ?", reponses: ["A. O(1)", "B. O(log n)", "C. O(n)", "D. O(n²)"], valid: 1 },
    { question: "Que signifie l'acronyme SQL ?", reponses: ["A. Standard Query Language", "B. Structured Query Language", "C. Server Query Language", "D. System Query Logic"], valid: 1 },
    { question: "Comment s'appelle le créateur d'origine du noyau Linux ?", reponses: ["A. Richard Stallman", "B. Steve Wozniak", "C. Linus Torvalds", "D. Ken Thompson"], valid: 2 },
    { question: "Quel patron de conception (design pattern) garantit qu'une classe n'a qu'une seule instance ?", reponses: ["A. Factory", "B. Observer", "C. Decorator", "D. Singleton"], valid: 3 },
    { question: "Quel était le nom du premier ordinateur électronique Turing-complet de l'histoire (1945) ?", reponses: ["A. Colossus", "B. ENIAC", "C. UNIVAC", "D. L'Altair 8800"], valid: 1 },
    { question: "En programmation orientée objet, quel concept permet à une classe d'hériter des propriétés d'une autre ?", reponses: ["A. Le polymorphisme", "B. L'encapsulation", "C. L'héritage", "D. L'abstraction"], valid: 2 },

    // --- THEME 10 : Sports Avancés et E-Sport ---
    { question: "Au jeu d'échecs, comment appelle-t-on la situation où un joueur n'est pas en échec mais n'a aucun coup légal possible ?", reponses: ["A. L'échec et mat", "B. Le pat", "C. Le roque", "D. L'en passant"], valid: 1 },
    { question: "Quel est le score d'une partie parfaite au bowling (uniquement des strikes) ?", reponses: ["A. 100", "B. 200", "C. 300", "D. 400"], valid: 2 },
    { question: "Quel pays détient le record absolu du nombre de médailles gagnées aux Jeux Olympiques d'hiver ?", reponses: ["A. Les États-Unis", "B. Le Canada", "C. La Russie", "D. La Norvège"], valid: 3 },
    { question: "Dans quel sport olympique exécute-t-on la technique du 'Fosbury Flop' ?", reponses: ["A. Le plongeon", "B. La gymnastique", "C. Le saut en hauteur", "D. Le saut à la perche"], valid: 2 },
    { question: "Quel est le seul sport de course où les athlètes doivent tourner le dos à la ligne d'arrivée ?", reponses: ["A. Le cyclisme sur piste", "B. La natation (dos crawlé)", "C. L'aviron", "D. Le lancer de poids"], valid: 2 },
    { question: "Qui détient l'incroyable record de 100 points marqués en un seul match de NBA ?", reponses: ["A. Michael Jordan", "B. Kobe Bryant", "C. LeBron James", "D. Wilt Chamberlain"], valid: 3 },
    { question: "Quelle est la longueur officielle d'un terrain de basketball professionnel (normes FIBA) ?", reponses: ["A. 24 mètres", "B. 28 mètres", "C. 32 mètres", "D. 35 mètres"], valid: 1 },
    { question: "Dans quelle ville moderne ont eu lieu les tout premiers Jeux Olympiques de l'ère moderne en 1896 ?", reponses: ["A. Paris", "B. Londres", "C. Rome", "D. Athènes"], valid: 3 },
    { question: "Quel est le nombre maximum de clubs qu'un golfeur professionnel a le droit d'emporter dans son sac ?", reponses: ["A. 10", "B. 12", "C. 14", "D. 16"], valid: 2 },
    { question: "Dans l'univers de l'e-sport, quel jeu vidéo organise le gigantesque championnat du monde appelé 'The International' ?", reponses: ["A. League of Legends", "B. Counter-Strike", "C. Dota 2", "D. Valorant"], valid: 2 }
];